### PR TITLE
Added code to parse shareholding summary of company

### PR DESCRIPTION
**Pull request by iedr**
Related to Issue #1

### CODE REVIEW

**Comment by shashank-556** [comment]
@darensin01 Thank you for your contribution  but your method is not working it is returning the empty *default_return_dict* for all inputs . The problem is in the .text attribute in line 143, 156. 
1. Use .string instead of .text 
2. You will have to ignore the *t.string* values that return *None* so probably use a loop instead of comprehension
3. There is only one script with *trend_text_to_look_for* value so make trends a string instead of a list.
4. Probably use Regular Expressions to extract summary_json object.

Please commit these changes and add anything extra if you want . Create an issue if you want to add any new methods or features in the project. Please star the repository.

**Comment by iedr** [comment]
Hi @shashank-556, thanks for the review!

> it is returning the empty default_return_dict for all inputs . The problem is in the .text attribute in line 143, 156

That's strange, because when I run `python mcontrol.py RI`, it returns me the correct `dict`. If I use `.string` in line 143, an error will be thrown.

I will work on the other suggestions!

**Comment by shashank-556** [comment]
> That's strange, because when I run `python mcontrol.py RI`, it returns me the correct `dict`. If I use `.string` in line 143, an error will be thrown.
The error is being caused because few t.string objects are of None type. As I mentioned use a loop to ignore them.

**Comment by iedr** [comment]
Hi @shashank-556 I've changed my code according to your suggestions.

**Pull request merged**
